### ISSUE TITLE
Cookie refresh issue leads to 502 bad gateway  

### ISSUE THREAD

**Issue by philmas** [j4w8n/sveltekit-supabase-ssr#4]
Your thorough posts are helpful in understanding the ssr flow with supabase. I currently use your repository for setting up authentication. But I seem to repeatedly run into issues and have no clue how to resolve it. For that matter, I get the same issue with the supabase ssr setup (all in sveltekit).

After a while of not entering the website, I stumble upon a 502 Bad Gateway on entering the website again. After clearing my cookies, I can enter the website again. So it seems there is an issue with cookie setting/refreshing. 

When I investigate the logs I get a clear status 200 response for refreshing the token. There are no errors or issues to be found in the logs (on the contrary), but I still cannot enter until I clear my cookies. 

Do you have any knowledge or ideas what this could be? I could share some logs if that would be helpful, but perhaps there is an existing issue that might lead to what I am experiencing.

**Comment by j4w8n** [comment]
I've not heard of that before. Getting a 502 Bad Gateway seems a bit weird in relation to cookies. Are you getting that response from SvelteKit or are they getting it from Supabase?

**Comment by mitjakukovec** [comment]
> I have resolved the issue by adding the following to my proxy configuration:
> 
> ```
> proxy_buffer_size 128k;
> proxy_buffers 4 256k;
> proxy_busy_buffers_size 256k;
> large_client_header_buffers 4 16k;
> ```

I'm not a seasoned web developer, but I want to resolve the same issue you experienced.

Please show me where this cookie configuration is added according to the supabase documentation.
https://supabase.com/docs/guides/auth/server-side/sveltekit

Thank you for helping out!

**Comment by mitjakukovec** [comment]
> > > I have resolved the issue by adding the following to my proxy configuration:
> > > ```
> > > proxy_buffer_size 128k;
> > > proxy_buffers 4 256k;
> > > proxy_busy_buffers_size 256k;
> > > large_client_header_buffers 4 16k;
> > > ```
> > 
> > 
> > I'm not a seasoned web developer, but I want to resolve the same issue you experienced.
> > Please show me where this cookie configuration is added according to the supabase documentation. https://supabase.com/docs/guides/auth/server-side/sveltekit
> > Thank you for helping out!
> 
> The issue is not with supabase, so I cannot show you according to the supabase documentation.
> 
> In my case, I was using NGINX proxy manager. I have added this information in the proxy manager settings of the corresponding application routes.

In which section of the NGINX configuration is this configured?

I've configured these in the location `/` section
```
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
```

and the `large_client_header_buffers 4 16k;` in the server section

If I put `large_client_header_buffers 4 16k;` in the location section NGINX is reporting invalid configuration error
