### ISSUE TITLE
Reactivity Lost When Logging Out

### ISSUE THREAD

**Issue by MattHeslington** [j4w8n/sveltekit-supabase-ssr#9]
Hello,
I love your implementation of Supabase auth with SvelteKit, it's so clean.

 I just noticed there's something gone wrong that's affecting reactivity when logging out when using Svelte 5. Logging out does actually log the user out, but the UI's not reactive the same way it was under Svelte 4. Only a hard refresh updates the UI, whereas before, with Svelte 4, the UI updated, ie. showed the log-in button, as soon as the user logged out. I can't work out what the issue is.

I have a bare-bones recreation here [on GitHub](https://github.com/MattHeslington/svelte-5-auth-test) and [on StackBlitz](https://stackblitz.com/~/github.com/MattHeslington/svelte-5-auth-test?file=.env), just the env variables needed.

Any advice would be really, really appreciated!
Kind regards,
Matt

**Comment by j4w8n** [comment]
I'll take a look at mine and dig around. Thanks!

**Comment by j4w8n** [comment]
I'm about to dive into your repro, but my code directly from this repo works as expected when logging out. I tested OAuth, email/pass, and anonymous logins, while logging out from `/`, `app`, and `/self`.

**Comment by j4w8n** [comment]
@MattHeslington for whatever reason, it's the `use:enhance` on the forms that's causing the issue. I can remove that and it resolves the issue. I've tried doing the below, with `use:enhance` but it doesn't work - it's supposed to `invalidateAll: true`, per the redirect bulletpoint here: https://svelte.dev/docs/kit/form-actions#Progressive-enhancement-Customising-use:enhance.

```js
<form method="POST" action="auth?/signout" use:enhance={
  () => {
    return async ({ result }) => {
      if (result.type === 'redirect') {
        await applyAction(result)
      }
    }
  }
}>
  <button>Logout</button>
</form>
```

**Comment by MattHeslington** [comment]
@j4w8n Ah, that's a simple fix! I didn't think of that and was focusing on the reactivity in the root layout instead. I'll try a few things with the use:enhance today to see if I can get it to work

**Comment by j4w8n** [comment]
@MattHeslington are we good to close this issue?

**Comment by MattHeslington** [comment]
Yes!
